# Generated by Django 4.0.6 on 2022-07-13 18:15

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
